### ISSUE TITLE
router selector issue

### ISSUE THREAD

**Issue by PasNinii** [nilsmehlhorn/ngrx-issue-tracker#1]
Hi, 

First of all, congrats for your book, it's really well written.

However, I wanted to try some stuff doing a project using angular 12 and ngrx 12. I am stuck with my `ArticleCollectionService `that is really similar to the `IssueCollectionService` in the book. 

This line give me the following error:
```
No overload matches this call.
  Overload 1 of 9, '(mapFn: (state: EntityCache) => Article | undefined): Observable<Article | undefined>', gave the following error.
    Argument of type 'MemoizedSelector<RootState, Article | undefined, DefaultProjectorFn<Article | undefined>>' is not assignable to parameter of type '(state: EntityCache) => Article | undefined'.
      Types of parameters 'state' and 'state' are incompatible.
        Property 'router' is missing in type 'EntityCache' but required in type 'RootState'.
  Overload 2 of 9, '(key: string | number): Observable<EntityCollection<any>>', gave the following error.
    Argument of type 'MemoizedSelector<RootState, Article | undefined, DefaultProjectorFn<Article | undefined>>' is not assignable to parameter of type 'string | number'.
      Type 'MemoizedSelector<RootState, Article | undefined, DefaultProjectorFn<Article | undefined>>' is not assignable to type 'number'
```

I think it's related to some interface declaration but after trying different things I don't manage to find where it is. I also tried on your repo and it seems that upgrading to angular & ngrx 12 give the same error. 

By any chance do you know what upgrade could cause this ?

**Comment by nilsmehlhorn** [comment]
Hey @PasNinii, thanks for the kind words. Would you be able to provide some code or even a reproduction on something like StackBlitz? Pretty hard to investigate the problem from the error message alone.

I'm planning to upgrade the repo and the book to Angular 12, just got to find some time for that.

**Comment by PasNinii** [comment]
In this repo i reproduced the code that triggers the error: https://github.com/PasNinii/duplicate-ngrx-issue

There are two points that triggers error for me compared to your repo:

- `export const selectActiveId = fromRouter.selectRouteParam('id');` , `fromRouter.selectRouteParam` returns `const selectRouteParam: (param: string) => MemoizedSelector<RootState, string | undefined, DefaultProjectorFn<string | undefined>>`
    - The fact the it can be undefined forced me to write `entities[id!]` in the `selectActive`
    - From what I saw, before it wasn't returning undefined. And I don't understand why it does, because when I use this selector I know my `:id` will be defined in the `routerParams`, except if now it requires that we specify something upon initialization
    
- ` this.articles$ = this.store.select(fromArticle.selectActive)` in **ArtcileCollectionService** returns an error that  i pointed out in my last comments. It seems that I cannot access `RootState.router`. It's like if I had to inject it in my `ArticleCollectionService`

Could it be because, they want to enforce the use of 

- `EntityCollectionServiceBase.` 
    - `getByKey(key: any, options?: EntityActionOptions): Observable<T>;`
    - `update(entity: Partial<T>, options?: EntityActionOptions): Observable<T>` directly from the component ? 

  Thank you for you time, and I look forward to your updates regarding angular 12 😉
